preferences:
  monitoringPeriod: 0
  rangeFrom: 0.0
  rangeTo: 0.1
  clkFreq: 48_000_000               # 48MHz
  extClkFreq: 12_000_000            # 12MHz
  waitMs: 0
  onlyChanges: true
  outputs: [ "INTERRUPT" ]
  gui: TABLE                # GRAPH | TABLE
  timeUnit: ms              # ms | us | ns

events:
  - start: 0.010        # s
    period: 0.010       # s, 0 == one–shot
    repeat: 5
    type:   TOGGLE_BIT
    reg:    0xE000E010
    bit:    1
